# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(max_length=50, null=True, verbose_name='字体图标'),
        ),
    ]
